export const ActionTypes = {
  LOGIN_ERROR: "LOGIN_ERROR",
  SIGNUP_ERROR: "SIGNUP_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
};
